'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ACDVentas.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;xml&gt;
        '''   &lt;sql&gt;
        '''      &lt;titulo&gt;DDirecciones.DIRECS_TodosAyuda&lt;/titulo&gt;
        '''      &lt;descripcion&gt;Obtener las direcciones de una entidad especifica&lt;/descripcion&gt;
        '''      &lt;code&gt;
        '''			SELECT top 100 0 As Codigo
        '''				,m_Dir.UBIGO_Codigo As Ubigeo
        '''				,m_Dir.ENTID_Direccion As Direccion
        '''				,Dep.UBIGO_Descripcion As Departamento
        '''				,Prov.UBIGO_Descripcion As Provincia
        '''				,Dis.UBIGO_Descripcion As Distrito
        '''			FROM Entidades As m_Dir
        '''				Inner Join Ubigeos As Dep On Dep.UBIGO_Codigo = Left(m_Dir.UBIGO_Codigo, 2)
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sql() As String
            Get
                Return ResourceManager.GetString("sql", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
