'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ACEVentas.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_GestionOrdenes&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;GESTOR&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_GestionOrdenes&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;GESTOR_Codigo&quot;&gt;GESTOR_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ALMAC_Id&quot;&gt;ALMAC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_CodigoEncargado&quot;&gt;ENTID_CodigoEncargado&lt;/CCampo&gt;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_GestionOrdenes() As String
            Get
                Return ResourceManager.GetString("xmlABAS_GestionOrdenes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_GestionOrdenesDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;GESTOD&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_GestionOrdenesDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;GESTOR_Codigo&quot;&gt;GESTOR_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;GESTOD_Item&quot;&gt;GESTOD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;GESTOD_CodigoOC&quot;&gt;GESTOD_CodigoOC&lt;/ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_GestionOrdenesDetalle() As String
            Get
                Return ResourceManager.GetString("xmlABAS_GestionOrdenesDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_OrdenesProduccion&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ORDEN&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_OrdenesProduccion&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDEN_Codigo&quot;&gt;ORDEN_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ORDEN_CodReferencia&quot;&gt;ORDEN_CodReferencia&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_CodigoEncargado&quot;&gt;ENTID_ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_OrdenesProduccion() As String
            Get
                Return ResourceManager.GetString("xmlABAS_OrdenesProduccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_OrdenesProduccionDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ORDET&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_OrdenesProduccionDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDEN_Codigo&quot;&gt;ORDEN_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDET_orden&quot;&gt;ORDET_orden&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ORDET_Item&quot;&gt;ORDET_Item&lt;/CCampo&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_OrdenesProduccionDetalle() As String
            Get
                Return ResourceManager.GetString("xmlABAS_OrdenesProduccionDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_PedidoTransformacion&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;PEDID&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_PedidoTransformacion&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PEDID_CodigoTrans&quot;&gt;PEDID_CodigoTrans&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_CodigoEncargado&quot;&gt;ENTID_CodigoEncargado&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PEDID_Des [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_PedidoTransformacion() As String
            Get
                Return ResourceManager.GetString("xmlABAS_PedidoTransformacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_PedidoTransformacionDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;PEDID&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_PedidoTransformacionDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PEDID_CodigoTrans&quot;&gt;PEDID_CodigoTrans&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PEDID_Item&quot;&gt;PEDID_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ART [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_PedidoTransformacionDetalle() As String
            Get
                Return ResourceManager.GetString("xmlABAS_PedidoTransformacionDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Almacenes&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;ALMAC&quot;&gt;
        '''  &lt;Nombre&gt;Almacenes&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ALMAC_Id&quot;&gt;ALMAC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;SUCUR_Id&quot;&gt;SUCUR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlAlmacenes() As String
            Get
                Return ResourceManager.GetString("xmlAlmacenes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ArticDestinos&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;ARTIC&quot;&gt;
        '''  &lt;Nombre&gt;ArticDestinos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_CodigoDestino&quot;&gt;ARTIC_CodigoDestino&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ARTDE_UsrCrea&quot;&gt;ARTDE_UsrCrea&lt;/CCampo&gt;
        '''    &lt;CCampo Identity [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlArticDestinos() As String
            Get
                Return ResourceManager.GetString("xmlArticDestinos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Articulos&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;ARTIC&quot;&gt;
        '''  &lt;Nombre&gt;Articulos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;LINEA_Codigo&quot;&gt;LINEA_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoProducto&quot;&gt;TIPOS_CodTipoProducto&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; F [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlArticulos() As String
            Get
                Return ResourceManager.GetString("xmlArticulos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Auditoria&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;AUDIT&quot;&gt;
        '''  &lt;Nombre&gt;Auditoria&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;AUDIT_Id&quot;&gt;AUDIT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;APLIC_Codigo&quot;&gt;APLIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlAuditoria() As String
            Get
                Return ResourceManager.GetString("xmlAuditoria", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Bancos&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;BANCO&quot;&gt;
        '''  &lt;Nombre&gt;Bancos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;BANCO_Id&quot;&gt;BANCO_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;BANCO_Descripcion&quot;&gt;BANCO_Descripcion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;BANCO_DescCorta&quot;&gt;BANCO_DescCorta&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; Pr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlBancos() As String
            Get
                Return ResourceManager.GetString("xmlBancos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Clientes&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;CLIEN&quot;&gt;
        '''  &lt;Nombre&gt;Clientes&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_CodigoVendedor&quot;&gt;ENTID_CodigoVendedor&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; Forei [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlClientes() As String
            Get
                Return ResourceManager.GetString("xmlClientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Color&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;COLOR&quot;&gt;
        '''  &lt;Nombre&gt;Color&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;COLOR_Id&quot;&gt;COLOR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;COLOR_Codigo&quot;&gt;COLOR_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;COLOR_Descripcion&quot;&gt;COLOR_Descripcion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlColor() As String
            Get
                Return ResourceManager.GetString("xmlColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Conductores&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;CONDU&quot;&gt;
        '''  &lt;Nombre&gt;Conductores&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;CONDU_Licencia&quot;&gt;CONDU_Licencia&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;CONDU_Sigla&quot;&gt;CONDU_Sigla&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlConductores() As String
            Get
                Return ResourceManager.GetString("xmlConductores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;CONT_DocsPercepcion&quot; Esquema=&quot;Contabilidad&quot; Prefijo=&quot;DOCPE&quot;&gt;
        '''  &lt;Nombre&gt;CONT_DocsPercepcion&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Contabilidad&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCPE_Codigo&quot;&gt;DOCPE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''    &lt;C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlCONT_DocsPercepcion() As String
            Get
                Return ResourceManager.GetString("xmlCONT_DocsPercepcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;CONT_DocsPercepcionDetalle&quot; Esquema=&quot;Contabilidad&quot; Prefijo=&quot;DOCPD&quot;&gt;
        '''  &lt;Nombre&gt;CONT_DocsPercepcionDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Contabilidad&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCPE_Codigo&quot;&gt;DOCPE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCPD_Item&quot;&gt;DOCPD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoDocumento&quot;&gt;TIPOS_Cod [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlCONT_DocsPercepcionDetalle() As String
            Get
                Return ResourceManager.GetString("xmlCONT_DocsPercepcionDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Correlativos&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;CORRE&quot;&gt;
        '''  &lt;Nombre&gt;Correlativos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;CORRE_Id&quot;&gt;CORRE_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;SUCUR_Id&quot;&gt;SUCUR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlCorrelativos() As String
            Get
                Return ResourceManager.GetString("xmlCorrelativos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Cuentas&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;CUENT&quot;&gt;
        '''  &lt;Nombre&gt;Cuentas&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;CUENT_Id&quot;&gt;CUENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;BANCO_Id&quot;&gt;BANCO_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoCuenta&quot;&gt;TIPOS_CodTipoCuenta&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlCuentas() As String
            Get
                Return ResourceManager.GetString("xmlCuentas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DESP_GuiaRSalidas&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;GUISA&quot;&gt;
        '''  &lt;Nombre&gt;DESP_GuiaRSalidas&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;SALID_Id&quot;&gt;SALID_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;VEHIC_Id&quot;&gt;VEHIC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDESP_GuiaRSalidas() As String
            Get
                Return ResourceManager.GetString("xmlDESP_GuiaRSalidas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DESP_Salidas&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;PVENT&quot;&gt;
        '''  &lt;Nombre&gt;DESP_Salidas&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;SALID_Id&quot;&gt;SALID_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;VEHIC_Id&quot;&gt;VEHIC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDESP_Salidas() As String
            Get
                Return ResourceManager.GetString("xmlDESP_Salidas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Direcciones&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;DIREC&quot;&gt;
        '''  &lt;Nombre&gt;Direcciones&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DIREC_Id&quot;&gt;DIREC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;UBIGO_Codigo&quot;&gt;UBIGO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryK [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDirecciones() As String
            Get
                Return ResourceManager.GetString("xmlDirecciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DIST_GuiasRemision&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;GUIAR&quot;&gt;
        '''  &lt;Nombre&gt;DIST_GuiasRemision&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;GUIAR_Codigo&quot;&gt;GUIAR_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDIST_GuiasRemision() As String
            Get
                Return ResourceManager.GetString("xmlDIST_GuiasRemision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DIST_GuiasRemisionDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;GUIRD&quot;&gt;
        '''  &lt;Nombre&gt;DIST_GuiasRemisionDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;GUIAR_Codigo&quot;&gt;GUIAR_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;GUIRD_Item&quot;&gt;GUIRD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;GUIRD_Lote&quot;&gt;GUIRD_Lote&lt;/CCampo&gt;
        '''    &lt;CCa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDIST_GuiasRemisionDetalle() As String
            Get
                Return ResourceManager.GetString("xmlDIST_GuiasRemisionDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DIST_Ordenes&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ORDEN&quot;&gt;
        '''  &lt;Nombre&gt;DIST_Ordenes&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDEN_Codigo&quot;&gt;ORDEN_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_CodigoCliente&quot;&gt;ENTID_CodigoCliente&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoMoneda&quot;&gt;TIPOS_CodTipoMoneda&lt;/CCampo&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDIST_Ordenes() As String
            Get
                Return ResourceManager.GetString("xmlDIST_Ordenes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DIST_OrdenesDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ORDET&quot;&gt;
        '''  &lt;Nombre&gt;DIST_OrdenesDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDEN_Codigo&quot;&gt;ORDEN_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDET_Item&quot;&gt;ORDET_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ORDET_ItemDocumento&quot;&gt;ORDET_ItemDocumento&lt;/CCampo&gt;
        '''   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDIST_OrdenesDetalle() As String
            Get
                Return ResourceManager.GetString("xmlDIST_OrdenesDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Entidades&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;ENTID&quot;&gt;
        '''  &lt;Nombre&gt;Entidades&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoDocumento&quot;&gt;TIPOS_CodTipoDocumento&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;UBIGO_Codigo&quot;&gt;UBIGO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlEntidades() As String
            Get
                Return ResourceManager.GetString("xmlEntidades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;EntidadesPadrones&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;ENPAD&quot;&gt;
        '''  &lt;Nombre&gt;EntidadesPadrones&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENPAD_Id&quot;&gt;ENPAD_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoPadron&quot;&gt;TIPOS_CodTipoPadron&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlEntidadesPadrones() As String
            Get
                Return ResourceManager.GetString("xmlEntidadesPadrones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;EntidadesRoles&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;ENTID&quot;&gt;
        '''  &lt;Nombre&gt;EntidadesRoles&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ROLES_Id&quot;&gt;ROLES_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENROL_UsrCrea&quot;&gt;ENROL_UsrCrea&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlEntidadesRoles() As String
            Get
                Return ResourceManager.GetString("xmlEntidadesRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;EntidadRelacion&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;ENTRE&quot;&gt;
        '''  &lt;Nombre&gt;EntidadRelacion&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTRE_Numero&quot;&gt;ENTRE_Numero&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_CodRelacion&quot;&gt;ENTID_CodRelacion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlEntidadRelacion() As String
            Get
                Return ResourceManager.GetString("xmlEntidadRelacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Lineas&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;LINEA&quot;&gt;
        '''  &lt;Nombre&gt;Lineas&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;LINEA_Codigo&quot;&gt;LINEA_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;LINEA_CodPadre&quot;&gt;LINEA_CodPadre&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoComision&quot;&gt;TIPOS_CodTipoComision&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; For [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlLineas() As String
            Get
                Return ResourceManager.GetString("xmlLineas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Parametros&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;PARMT&quot;&gt;
        '''  &lt;Nombre&gt;Parametros&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PARMT_Id&quot;&gt;PARMT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;APLIC_Codigo&quot;&gt;APLIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlParametros() As String
            Get
                Return ResourceManager.GetString("xmlParametros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Periodos&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;PERIO&quot;&gt;
        '''  &lt;Nombre&gt;Periodos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PERIO_Codigo&quot;&gt;PERIO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PERIO_Descripcion&quot;&gt;PERIO_Descripcion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PERIO_StockActivo&quot;&gt;PERIO_StockActivo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; F [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlPeriodos() As String
            Get
                Return ResourceManager.GetString("xmlPeriodos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Precios&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;PRECI&quot;&gt;
        '''  &lt;Nombre&gt;Precios&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoMoneda&quot;&gt;TIPOS_CodTipoMoneda&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlPrecios() As String
            Get
                Return ResourceManager.GetString("xmlPrecios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Proveedores&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;PROVE&quot;&gt;
        '''  &lt;Nombre&gt;Proveedores&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PROVE_Atencion&quot;&gt;PROVE_Atencion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PROVE_Contacto&quot;&gt;PROVE_Contacto&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; Foreign [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlProveedores() As String
            Get
                Return ResourceManager.GetString("xmlProveedores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Prueba&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;PRUEB&quot;&gt;
        '''  &lt;Nombre&gt;Prueba&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PRUEB_Id&quot;&gt;PRUEB_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PRUEB_Descripcion&quot;&gt;PRUEB_Descripcion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PRUEB_Activo&quot;&gt;PRUEB_Activo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryK [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlPrueba() As String
            Get
                Return ResourceManager.GetString("xmlPrueba", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;PruebaTipo&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;PRUTI&quot;&gt;
        '''  &lt;Nombre&gt;PruebaTipo&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PRUTI_Id&quot;&gt;PRUTI_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PRUTI_Descripcion&quot;&gt;PRUTI_Descripcion&lt;/CCampo&gt;
        '''  &lt;/Campos&gt;
        '''  &lt;CPrimarios&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PRUTI_Id&quot;&gt;PRUTI_Id&lt;/CCampo&gt;
        '''  &lt;/CPrimarios&gt;
        '''   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlPruebaTipo() As String
            Get
                Return ResourceManager.GetString("xmlPruebaTipo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;PuntoVenta&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;PVENT&quot;&gt;
        '''  &lt;Nombre&gt;PuntoVenta&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;SUCUR_Id&quot;&gt;SUCUR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xml [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlPuntoVenta() As String
            Get
                Return ResourceManager.GetString("xmlPuntoVenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Roles&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;ROLES&quot;&gt;
        '''  &lt;Nombre&gt;Roles&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ROLES_Id&quot;&gt;ROLES_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ROLES_Descripcion&quot;&gt;ROLES_Descripcion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ROLES_UsrCrea&quot;&gt;ROLES_UsrCrea&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryK [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlRoles() As String
            Get
                Return ResourceManager.GetString("xmlRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Stocks&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;STOCK&quot;&gt;
        '''  &lt;Nombre&gt;Stocks&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ALMAC_Id&quot;&gt;ALMAC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PERIO_Codigo&quot;&gt;PERIO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xml [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlStocks() As String
            Get
                Return ResourceManager.GetString("xmlStocks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Sucursales&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;SUCUR&quot;&gt;
        '''  &lt;Nombre&gt;Sucursales&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;SUCUR_Id&quot;&gt;SUCUR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;UBIGO_Codigo&quot;&gt;UBIGO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlSucursales() As String
            Get
                Return ResourceManager.GetString("xmlSucursales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Telefonos&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;TELEF&quot;&gt;
        '''  &lt;Nombre&gt;Telefonos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;TELEF_ID&quot;&gt;TELEF_ID&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TELEF_Telefono&quot;&gt;TELEF_Telefono&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryK [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTelefonos() As String
            Get
                Return ResourceManager.GetString("xmlTelefonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_Caja&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;CAJA&quot;&gt;
        '''  &lt;Nombre&gt;TESO_Caja&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;CAJA_Id&quot;&gt;CAJA_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;BANCO_Id&quot;&gt;BANCO_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmln [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_Caja() As String
            Get
                Return ResourceManager.GetString("xmlTESO_Caja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_CajaChicaIngreso&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;CAJAC&quot;&gt;
        '''  &lt;Nombre&gt;TESO_CajaChicaIngreso&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;CAJAC_Id&quot;&gt;CAJAC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_CajaChicaIngreso() As String
            Get
                Return ResourceManager.GetString("xmlTESO_CajaChicaIngreso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_CajaChicaPagos&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;CAJAP&quot;&gt;
        '''  &lt;Nombre&gt;TESO_CajaChicaPagos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;CAJAC_Id&quot;&gt;CAJAC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;CAJAP_Item&quot;&gt;CAJAP_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; Foreign [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_CajaChicaPagos() As String
            Get
                Return ResourceManager.GetString("xmlTESO_CajaChicaPagos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_CajaDocsPago&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;CAJA&quot;&gt;
        '''  &lt;Nombre&gt;TESO_CajaDocsPago&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;CAJA_Codigo&quot;&gt;CAJA_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DPAGO_Id&quot;&gt;DPAGO_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_CajaDocsPago() As String
            Get
                Return ResourceManager.GetString("xmlTESO_CajaDocsPago", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_DocsPagos&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;DPAGO&quot;&gt;
        '''  &lt;Nombre&gt;TESO_DocsPagos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DPAGO_Id&quot;&gt;DPAGO_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;BANCO_Id&quot;&gt;BANCO_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; Primar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_DocsPagos() As String
            Get
                Return ResourceManager.GetString("xmlTESO_DocsPagos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_Documentos&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;DOCUS&quot;&gt;
        '''  &lt;Nombre&gt;TESO_Documentos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCUS_Codigo&quot;&gt;DOCUS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoMoneda&quot;&gt;TIPOS_CodTipoMoneda&lt;/CCampo&gt;
        '''    &lt;C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_Documentos() As String
            Get
                Return ResourceManager.GetString("xmlTESO_Documentos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_DocumentosDetalle&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;DCDET&quot;&gt;
        '''  &lt;Nombre&gt;TESO_DocumentosDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCUS_Codigo&quot;&gt;DOCUS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DCDET_Item&quot;&gt;DCDET_Item&lt;/CCampo&gt;
        '''    &lt;CCamp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_DocumentosDetalle() As String
            Get
                Return ResourceManager.GetString("xmlTESO_DocumentosDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_PendientesCaja&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;PCAJA&quot;&gt;
        '''  &lt;Nombre&gt;TESO_PendientesCaja&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PCAJA_Id&quot;&gt;PCAJA_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoMoneda&quot;&gt;TIPOS_CodTipoMoneda&lt;/CCampo&gt;
        '''    &lt;CCampo Id [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_PendientesCaja() As String
            Get
                Return ResourceManager.GetString("xmlTESO_PendientesCaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_PendientesCancelacion&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;PCCAJ&quot;&gt;
        '''  &lt;Nombre&gt;TESO_PendientesCancelacion&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PCAJA_Id&quot;&gt;PCAJA_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PCCAJ_Item&quot;&gt;PCCAJ_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_PendientesCancelacion() As String
            Get
                Return ResourceManager.GetString("xmlTESO_PendientesCancelacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_Recibos&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;RECIB&quot;&gt;
        '''  &lt;Nombre&gt;TESO_Recibos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;RECIB_Codigo&quot;&gt;RECIB_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoMoneda&quot;&gt;TIPOS_CodTipoMoneda&lt;/CCampo&gt;
        '''    &lt;CCampo  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_Recibos() As String
            Get
                Return ResourceManager.GetString("xmlTESO_Recibos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_Sencillo&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;SENCI&quot;&gt;
        '''  &lt;Nombre&gt;TESO_Sencillo&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;SENCI_Id&quot;&gt;SENCI_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;SENCI_Fecha&quot;&gt;SENCI_Fecha&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; Pr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_Sencillo() As String
            Get
                Return ResourceManager.GetString("xmlTESO_Sencillo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TESO_SIniciales&quot; Esquema=&quot;Tesoreria&quot; Prefijo=&quot;SINIC&quot;&gt;
        '''  &lt;Nombre&gt;TESO_SIniciales&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Tesoreria&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;1&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;SINIC_Id&quot;&gt;SINIC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTESO_SIniciales() As String
            Get
                Return ResourceManager.GetString("xmlTESO_SIniciales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TipoCambio&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;TIPOC&quot;&gt;
        '''  &lt;Nombre&gt;TipoCambio&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;TIPOC_Fecha&quot;&gt;TIPOC_Fecha&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOC_FechaC&quot;&gt;TIPOC_FechaC&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOC_CompraOficina&quot;&gt;TIPOC_CompraOficina&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; Forei [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTipoCambio() As String
            Get
                Return ResourceManager.GetString("xmlTipoCambio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TipoColor&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;TPCOL&quot;&gt;
        '''  &lt;Nombre&gt;TipoColor&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;1&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;TPCOL_Id&quot;&gt;TPCOL_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TPCOL_Codigo&quot;&gt;TPCOL_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TPCOL_Descripcion&quot;&gt;TPCOL_Descripcion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; Pr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTipoColor() As String
            Get
                Return ResourceManager.GetString("xmlTipoColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TipoDocumento&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;TDOCU&quot;&gt;
        '''  &lt;Nombre&gt;TipoDocumento&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;TDOCU_Id&quot;&gt;TDOCU_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TDOCU_Codigo&quot;&gt;TDOCU_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TDOCU_Descripcion&quot;&gt;TDOCU_Descripcion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTipoDocumento() As String
            Get
                Return ResourceManager.GetString("xmlTipoDocumento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Tipos&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;TIPOS&quot;&gt;
        '''  &lt;Nombre&gt;Tipos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;TIPOS_Codigo&quot;&gt;TIPOS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_Descripcion&quot;&gt;TIPOS_Descripcion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_DescLarga&quot;&gt;TIPOS_DescLarga&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTipos() As String
            Get
                Return ResourceManager.GetString("xmlTipos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TRAN_Vehiculos&quot; Esquema=&quot;Transportes&quot; Prefijo=&quot;VEHIC&quot;&gt;
        '''  &lt;Nombre&gt;TRAN_Vehiculos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Transportes&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;VEHIC_Id&quot;&gt;VEHIC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoCombustible&quot;&gt;TIPOS_CodTipoCombustible&lt;/CCampo&gt;
        '''    &lt;CCamp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTRAN_Vehiculos() As String
            Get
                Return ResourceManager.GetString("xmlTRAN_Vehiculos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;TRAN_VehiculosConductores&quot; Esquema=&quot;Transporte&quot; Prefijo=&quot;VHCON&quot;&gt;
        '''  &lt;Nombre&gt;TRAN_VehiculosConductores&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Transporte&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;1&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;VHCON_Id&quot;&gt;VHCON_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;VEHIC_Id&quot;&gt;VEHIC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Id [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTRAN_VehiculosConductores() As String
            Get
                Return ResourceManager.GetString("xmlTRAN_VehiculosConductores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Ubigeos&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;UBIGO&quot;&gt;
        '''  &lt;Nombre&gt;Ubigeos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;UBIGO_Codigo&quot;&gt;UBIGO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;UBIGO_CodPadre&quot;&gt;UBIGO_CodPadre&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;UBIGO_Descripcion&quot;&gt;UBIGO_Descripcion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlUbigeos() As String
            Get
                Return ResourceManager.GetString("xmlUbigeos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;UsuariosPorAlmacen&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;USUAR&quot;&gt;
        '''  &lt;Nombre&gt;UsuariosPorAlmacen&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;SUCUR_Id&quot;&gt;SUCUR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ALMAC_Id&quot;&gt;ALMAC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; Pr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlUsuariosPorAlmacen() As String
            Get
                Return ResourceManager.GetString("xmlUsuariosPorAlmacen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;UsuariosPorPuntoVenta&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;USUAR&quot;&gt;
        '''  &lt;Nombre&gt;UsuariosPorPuntoVenta&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;SUCUR_Id&quot;&gt;SUCUR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlUsuariosPorPuntoVenta() As String
            Get
                Return ResourceManager.GetString("xmlUsuariosPorPuntoVenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_DocsRelacion&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;DOCRE&quot;&gt;
        '''  &lt;Nombre&gt;VENT_DocsRelacion&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCVE_CodReferencia&quot;&gt;DOCVE_CodReferencia&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;DOCRE_NCPorcentaje&quot;&gt;DOCRE_NCPorcentaje&lt;/CCamp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_DocsRelacion() As String
            Get
                Return ResourceManager.GetString("xmlVENT_DocsRelacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_DocsVenta&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;DOCVE&quot;&gt;
        '''  &lt;Nombre&gt;VENT_DocsVenta&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;SUCUR_Id&quot;&gt;SUCUR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_DocsVenta() As String
            Get
                Return ResourceManager.GetString("xmlVENT_DocsVenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_DocsVentaDetalle&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;DOCVD&quot;&gt;
        '''  &lt;Nombre&gt;VENT_DocsVentaDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCVD_Item&quot;&gt;DOCVD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_DocsVentaDetalle() As String
            Get
                Return ResourceManager.GetString("xmlVENT_DocsVentaDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_DocsVentaPagos&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;DVEPG&quot;&gt;
        '''  &lt;Nombre&gt;VENT_DocsVentaPagos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DPAGO_Id&quot;&gt;DPAGO_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_DocsVentaPagos() As String
            Get
                Return ResourceManager.GetString("xmlVENT_DocsVentaPagos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_ListaPrecios&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;LPREC&quot;&gt;
        '''  &lt;Nombre&gt;VENT_ListaPrecios&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;LPREC_Id&quot;&gt;LPREC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;LPREC_Codigo&quot;&gt;LPREC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; Forei [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_ListaPrecios() As String
            Get
                Return ResourceManager.GetString("xmlVENT_ListaPrecios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_ListaPreciosArticulos&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;ALPRE&quot;&gt;
        '''  &lt;Nombre&gt;VENT_ListaPreciosArticulos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;LPREC_Id&quot;&gt;LPREC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_ListaPreciosArticulos() As String
            Get
                Return ResourceManager.GetString("xmlVENT_ListaPreciosArticulos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_Pedidos&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;PEDID&quot;&gt;
        '''  &lt;Nombre&gt;VENT_Pedidos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PEDID_Codigo&quot;&gt;PEDID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_Pedidos() As String
            Get
                Return ResourceManager.GetString("xmlVENT_Pedidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_PedidosDetalle&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;PDDET&quot;&gt;
        '''  &lt;Nombre&gt;VENT_PedidosDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PEDID_Codigo&quot;&gt;PEDID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PDDET_Item&quot;&gt;PDDET_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_PedidosDetalle() As String
            Get
                Return ResourceManager.GetString("xmlVENT_PedidosDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_ProductoAdicionales&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;ARTIC&quot;&gt;
        '''  &lt;Nombre&gt;VENT_ProductoAdicionales&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ARTIC_Cuenta&quot;&gt;ARTIC_Cuenta&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ARTIC_CuentaCos&quot;&gt;ARTIC_CuentaCos&lt;/CCampo&gt;
        '''   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_ProductoAdicionales() As String
            Get
                Return ResourceManager.GetString("xmlVENT_ProductoAdicionales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_PVentDocumento&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;PVDOCU&quot;&gt;
        '''  &lt;Nombre&gt;VENT_PVentDocumento&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVDOCU_Id&quot;&gt;PVDOCU_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;SUCUR_Id&quot;&gt;SUCUR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; Foreig [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_PVentDocumento() As String
            Get
                Return ResourceManager.GetString("xmlVENT_PVentDocumento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_UsuariosPorPuntoVenta&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;VENT&quot;&gt;
        '''  &lt;Nombre&gt;VENT_UsuariosPorPuntoVenta&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Id&quot;&gt;ENTID_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_UsuariosPorPuntoVenta() As String
            Get
                Return ResourceManager.GetString("xmlVENT_UsuariosPorPuntoVenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VerStockPtoVenta&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;VERST&quot;&gt;
        '''  &lt;Nombre&gt;VerStockPtoVenta&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ALMAC_Id&quot;&gt;ALMAC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;VSPVA_UsrCrea&quot;&gt;VSPVA_UsrCrea&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; Prim [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVerStockPtoVenta() As String
            Get
                Return ResourceManager.GetString("xmlVerStockPtoVenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Zonas&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;ZONAS&quot;&gt;
        '''  &lt;Nombre&gt;Zonas&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Descripcion&quot;&gt;ZONAS_Descripcion&lt;/CCampo&gt;
        '''  &lt;/Campos&gt;
        '''  &lt;CPrimarios&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''  &lt;/CPrimario [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlZonas() As String
            Get
                Return ResourceManager.GetString("xmlZonas", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
