'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ACELogistica.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_Costeos&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;COSTE&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_Costeos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCCO_Codigo&quot;&gt;DOCCO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_CodigoProveedor&quot;&gt;ENTID_CodigoProveedor&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCCD_Item&quot;&gt;DOCCD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_Costeos() As String
            Get
                Return ResourceManager.GetString("xmlABAS_Costeos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_CotizacionesCompra&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;COTCO&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_CotizacionesCompra&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;COTCO_Codigo&quot;&gt;COTCO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;SUCUR_Id&quot;&gt;SUCUR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_CotizacionesCompra() As String
            Get
                Return ResourceManager.GetString("xmlABAS_CotizacionesCompra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_CotizacionesCompraDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;COTCD&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_CotizacionesCompraDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;COTCO_Codigo&quot;&gt;COTCO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;COTCD_Item&quot;&gt;COTCD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_CotizacionesCompraDetalle() As String
            Get
                Return ResourceManager.GetString("xmlABAS_CotizacionesCompraDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_DocsCompra&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;DOCCO&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_DocsCompra&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCCO_Codigo&quot;&gt;DOCCO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_CodigoProveedor&quot;&gt;ENTID_CodigoProveedor&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_DocsCompra() As String
            Get
                Return ResourceManager.GetString("xmlABAS_DocsCompra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_DocsCompraDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;DOCCD&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_DocsCompraDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCCO_Codigo&quot;&gt;DOCCO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCCD_Item&quot;&gt;DOCCD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_CodigoProveedor&quot;&gt;ENTID_CodigoProveedor&lt;/C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_DocsCompraDetalle() As String
            Get
                Return ResourceManager.GetString("xmlABAS_DocsCompraDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_IngresosCompra&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;INGCO&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_IngresosCompra&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ALMAC_Id&quot;&gt;ALMAC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;INGCO_Id&quot;&gt;INGCO_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoDocumento&quot;&gt;TIPOS_CodTipoDocumento&lt;/CCampo&gt;
        '''    &lt;CCa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_IngresosCompra() As String
            Get
                Return ResourceManager.GetString("xmlABAS_IngresosCompra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_IngresosCompraDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;INGCD&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_IngresosCompraDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ALMAC_Id&quot;&gt;ALMAC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;INGCO_Id&quot;&gt;INGCO_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;INGCD_Item&quot;&gt;INGCD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_IngresosCompraDetalle() As String
            Get
                Return ResourceManager.GetString("xmlABAS_IngresosCompraDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_ListaPreciosCompra&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;LPRCO&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_ListaPreciosCompra&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_Codigo&quot;&gt;ENTID_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;TIPOS_CodTipoMoneda&quot;&gt;TIPOS_CodTipoMoneda&lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_ListaPreciosCompra() As String
            Get
                Return ResourceManager.GetString("xmlABAS_ListaPreciosCompra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_OrdenesCompra&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ORDCO&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_OrdenesCompra&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDCO_Codigo&quot;&gt;ORDCO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_CodigoProveedor&quot;&gt;ENTID_CodigoProveedor&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONA_Codigo&quot;&gt;ZONA_Codigo&lt;/CCampo&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_OrdenesCompra() As String
            Get
                Return ResourceManager.GetString("xmlABAS_OrdenesCompra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_OrdenesCompraDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ORDCD&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_OrdenesCompraDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDCO_Codigo&quot;&gt;ORDCO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDCD_Item&quot;&gt;ORDCD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''     [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_OrdenesCompraDetalle() As String
            Get
                Return ResourceManager.GetString("xmlABAS_OrdenesCompraDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ABAS_RelDocsCosteo&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;DOCCO&quot;&gt;
        '''  &lt;Nombre&gt;ABAS_RelDocsCosteo&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCCO_Codigo&quot;&gt;DOCCO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCCD_Item&quot;&gt;DOCCD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ENTID_CodigoProveedor&quot;&gt;ENTID_CodigoProveedor&lt;/CCampo&gt;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlABAS_RelDocsCosteo() As String
            Get
                Return ResourceManager.GetString("xmlABAS_RelDocsCosteo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;ArticDestinos&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;ARTIC&quot;&gt;
        '''  &lt;Nombre&gt;ArticDestinos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_CodigoDestino&quot;&gt;ARTIC_CodigoDestino&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ARTDE_UsrCrea&quot;&gt;ARTDE_UsrCrea&lt;/CCampo&gt;
        '''    &lt;CCampo Identity [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlArticDestinos() As String
            Get
                Return ResourceManager.GetString("xmlArticDestinos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Articulos&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;ARTIC&quot;&gt;
        '''  &lt;Nombre&gt;Articulos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;LINEA_Codigo&quot;&gt;LINEA_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoProducto&quot;&gt;TIPOS_CodTipoProducto&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; F [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlArticulos() As String
            Get
                Return ResourceManager.GetString("xmlArticulos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;CTRL_Arreglos&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ARREG&quot;&gt;
        '''  &lt;Nombre&gt;CTRL_Arreglos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARREG_Codigo&quot;&gt;ARREG_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoArreglo&quot;&gt;TIPOS_CodTipoArreglo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlCTRL_Arreglos() As String
            Get
                Return ResourceManager.GetString("xmlCTRL_Arreglos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;CTRL_ArreglosDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ARRDT&quot;&gt;
        '''  &lt;Nombre&gt;CTRL_ArreglosDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARREG_Codigo&quot;&gt;ARREG_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARRDT_Item&quot;&gt;ARRDT_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Id [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlCTRL_ArreglosDetalle() As String
            Get
                Return ResourceManager.GetString("xmlCTRL_ArreglosDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;CTRL_InventarioRotativo&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;INROT&quot;&gt;
        '''  &lt;Nombre&gt;CTRL_InventarioRotativo&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;INROT_Codigo&quot;&gt;INROT_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_CodigoResponsable&quot;&gt;ENTID_CodigoResponsable&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;INROT_Serie&quot;&gt;INROT_ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlCTRL_InventarioRotativo() As String
            Get
                Return ResourceManager.GetString("xmlCTRL_InventarioRotativo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;CTRL_InventarioRotativoDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;INROT&quot;&gt;
        '''  &lt;Nombre&gt;CTRL_InventarioRotativoDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;INROT_Codigo&quot;&gt;INROT_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;INROD_Item&quot;&gt;INROD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlCTRL_InventarioRotativoDetalle() As String
            Get
                Return ResourceManager.GetString("xmlCTRL_InventarioRotativoDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DIST_GuiasRemision&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;GUIAR&quot;&gt;
        '''  &lt;Nombre&gt;DIST_GuiasRemision&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;GUIAR_Codigo&quot;&gt;GUIAR_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDIST_GuiasRemision() As String
            Get
                Return ResourceManager.GetString("xmlDIST_GuiasRemision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DIST_GuiasRemisionDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;GUIRD&quot;&gt;
        '''  &lt;Nombre&gt;DIST_GuiasRemisionDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;GUIAR_Codigo&quot;&gt;GUIAR_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;GUIRD_Item&quot;&gt;GUIRD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''     [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDIST_GuiasRemisionDetalle() As String
            Get
                Return ResourceManager.GetString("xmlDIST_GuiasRemisionDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DIST_Ordenes&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ORDEN&quot;&gt;
        '''  &lt;Nombre&gt;DIST_Ordenes&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDEN_Codigo&quot;&gt;ORDEN_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ENTID_CodigoCliente&quot;&gt;ENTID_CodigoCliente&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoMoneda&quot;&gt;TIPOS_CodTipoMoneda&lt;/CCampo&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDIST_Ordenes() As String
            Get
                Return ResourceManager.GetString("xmlDIST_Ordenes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DIST_OrdenesDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ORDET&quot;&gt;
        '''  &lt;Nombre&gt;DIST_OrdenesDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDEN_Codigo&quot;&gt;ORDEN_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDET_Item&quot;&gt;ORDET_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ORDET_ItemDocumento&quot;&gt;ORDET_ItemDocumento&lt;/CCampo&gt;
        '''   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDIST_OrdenesDetalle() As String
            Get
                Return ResourceManager.GetString("xmlDIST_OrdenesDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DIST_OrdenesRecojo&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ORDRE&quot;&gt;
        '''  &lt;Nombre&gt;DIST_OrdenesRecojo&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDRE_Codigo&quot;&gt;ORDRE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ALMA_Id&quot;&gt;ALMA_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;1&quot; Foreign [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDIST_OrdenesRecojo() As String
            Get
                Return ResourceManager.GetString("xmlDIST_OrdenesRecojo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;DIST_OrdenesRecojoDetalle&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;ORDRE&quot;&gt;
        '''  &lt;Nombre&gt;DIST_OrdenesRecojoDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDRE_Codigo&quot;&gt;ORDRE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ORDRE_Item&quot;&gt;ORDRE_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''     [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlDIST_OrdenesRecojoDetalle() As String
            Get
                Return ResourceManager.GetString("xmlDIST_OrdenesRecojoDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;LOG_StockIniciales&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;STINI&quot;&gt;
        '''  &lt;Nombre&gt;LOG_StockIniciales&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PERIO_Codigo&quot;&gt;PERIO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;1&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;STINI_Id&quot;&gt;STINI_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlLOG_StockIniciales() As String
            Get
                Return ResourceManager.GetString("xmlLOG_StockIniciales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;LOG_Stocks&quot; Esquema=&quot;Logistica&quot; Prefijo=&quot;STOCK&quot;&gt;
        '''  &lt;Nombre&gt;LOG_Stocks&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Logistica&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PERIO_Codigo&quot;&gt;PERIO_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ALMAC_Id&quot;&gt;ALMAC_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlLOG_Stocks() As String
            Get
                Return ResourceManager.GetString("xmlLOG_Stocks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Precios&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;PRECI&quot;&gt;
        '''  &lt;Nombre&gt;Precios&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;ARTIC_Codigo&quot;&gt;ARTIC_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_CodTipoMoneda&quot;&gt;TIPOS_CodTipoMoneda&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlPrecios() As String
            Get
                Return ResourceManager.GetString("xmlPrecios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;PuntoVenta&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;PVENT&quot;&gt;
        '''  &lt;Nombre&gt;PuntoVenta&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;PVENT_Id&quot;&gt;PVENT_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;SUCUR_Id&quot;&gt;SUCUR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xml [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlPuntoVenta() As String
            Get
                Return ResourceManager.GetString("xmlPuntoVenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;Tipos&quot; Esquema=&quot;dbo&quot; Prefijo=&quot;TIPOS&quot;&gt;
        '''  &lt;Nombre&gt;Tipos&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;dbo&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;TIPOS_Codigo&quot;&gt;TIPOS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_Descripcion&quot;&gt;TIPOS_Descripcion&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;TIPOS_DescLarga&quot;&gt;TIPOS_DescLarga&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlTipos() As String
            Get
                Return ResourceManager.GetString("xmlTipos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_DocsRelacion&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;DOCRE&quot;&gt;
        '''  &lt;Nombre&gt;VENT_DocsRelacion&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCVE_CodReferencia&quot;&gt;DOCVE_CodReferencia&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;DOCRE_NCPorcentaje&quot;&gt;DOCRE_NCPorcentaje&lt;/CCamp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_DocsRelacion() As String
            Get
                Return ResourceManager.GetString("xmlVENT_DocsRelacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_DocsVenta&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;DOCVE&quot;&gt;
        '''  &lt;Nombre&gt;VENT_DocsVenta&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;SUCUR_Id&quot;&gt;SUCUR_Id&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_DocsVenta() As String
            Get
                Return ResourceManager.GetString("xmlVENT_DocsVenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        '''&lt;Tabla Nombre=&quot;VENT_DocsVentaDetalle&quot; Esquema=&quot;Ventas&quot; Prefijo=&quot;DOCVD&quot;&gt;
        '''  &lt;Nombre&gt;VENT_DocsVentaDetalle&lt;/Nombre&gt;
        '''  &lt;Esquema&gt;Ventas&lt;/Esquema&gt;
        '''  &lt;Campos&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCVE_Codigo&quot;&gt;DOCVE_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;0&quot; PrimaryKey=&quot;1&quot; xmlns=&quot;DOCVD_Item&quot;&gt;DOCVD_Item&lt;/CCampo&gt;
        '''    &lt;CCampo Identity=&quot;0&quot; ForeignKey=&quot;1&quot; PrimaryKey=&quot;0&quot; xmlns=&quot;ZONAS_Codigo&quot;&gt;ZONAS_Codigo&lt;/CCampo&gt;
        '''    &lt;CCampo Identi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlVENT_DocsVentaDetalle() As String
            Get
                Return ResourceManager.GetString("xmlVENT_DocsVentaDetalle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
